# include:
#   - compose.observability.yaml
services:
  faster-whisper-server:
    extends:
      file: compose.yaml
      service: faster-whisper-server
    image: fedirz/faster-whisper-server:latest-cpu
    build:
      args:
        BASE_IMAGE: ubuntu:24.04
    environment:
      - WHISPER__MODEL=Systran/faster-whisper-small
    volumes:
      - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub
volumes:
  hf-hub-cache:
